### ISSUE TITLE
[BUG] YouTube previews aren't linking or showing the current Live

### ISSUE THREAD

**Issue by jaylay99** [MarkM-dev/Previews#100]
When I peak the preview on a YouTube Live from the sidebar, it shows an old VOD I watched a while ago instead of the current Live, when I click it redirects me to the old VOD rather than the Live. Since it's been happening, I never had the current Live shown in previews or the proper redirect to it. **_Tested on Microsoft Edge browser_**

**Here is a video showing the issue :** 

https://user-images.githubusercontent.com/76778450/199614598-ab2a3933-ffb9-45ec-a4a5-e5b15da0dfac.mp4

**Comment by MarkM-dev** [comment]
next time it happens, screenshot: https://www.youtube.com/feed/subscriptions?flow=1

**Comment by jaylay99** [comment]
> next time it happens, screenshot: https://www.youtube.com/feed/subscriptions?flow=1

DrDisrespect is currently not live but I still see him in the sidebar : 
![image](https://user-images.githubusercontent.com/76778450/199802267-eb11e134-d30e-4beb-9634-7aa56694e3f6.png)

Here's what it looks like in the subscriptions feed : 
![image](https://user-images.githubusercontent.com/76778450/199802156-2ff5897c-04e4-46dd-9d98-9f896eb93043.png)

**Comment by MarkM-dev** [comment]
is it possible that another extension is interfering with data coming in from youtube and forcing some streamers to show?
maybe try on a different browser that is fresh and clean of extensions and see if it still happens?

**Comment by jaylay99** [comment]
> is it possible that another extension is interfering with data coming in from youtube and forcing some streamers to show? maybe try on a different browser that is fresh and clean of extensions and see if it still happens?

I tried on another browser (Chrome) and it worked fine (I had YouTube setting enabled and it wasn't showing any VODs) but that wasn't because of extensions because I tried again on Edge with ALL extensions turned off except for Previews and I still had the same issue.

**I had to reinstall Previews completely then import back my settings to have it fixed (Edge)** Idk if it's going to happen again though. My guess is maybe how Previews store save data?

**Comment by MarkM-dev** [comment]
not sure what happened, it looks like the background script returned a cached object instead of a new fetched one from the screenshots.
it's also possible that the extension lost permission to fetch from youtube (another user has reported that he needed to go to the extension settings in the browser settings page (he uses brave) and toggle the permission off and on again).
closing this for now as this doesn't seem to happen anywhere else and from checking everything looks correct.
reopen the issue if this happens again.
