### ISSUE TITLE
Channels list issue with favorite channels and youtube streams

### ISSUE THREAD

**Issue by MrSebros** [MarkM-dev/Previews#103]
![image](https://user-images.githubusercontent.com/118317033/202044442-42f31d12-cb90-4a40-be65-cf9c40ae493e.png)
![image](https://user-images.githubusercontent.com/118317033/202044458-d18b6814-e3aa-44e2-b38a-fa7a12fee64a.png)

**Comment by MarkM-dev** [comment]
try disabling all other extensions, then enable them one by one to see which on causes this to happen. (refresh twitch between changes)
