### ISSUE TITLE
Twitch Video previews are now filled with ads

### ISSUE THREAD

**Issue by jaylay99** [MarkM-dev/Previews#104]
Twitch recently changed their ad system and now I'm constantly getting ADs in video previews. Maybe having an option to add a proxy to bypass ads could be a thing?

![image](https://user-images.githubusercontent.com/76778450/202640677-29a52996-73f0-40f1-8c29-2fe10b4d01b1.png)

**Comment by Aghneel** [comment]
I'm also getting the same, is there a way to avoid that with script like https://github.com/pixeltris/TwitchAdSolutions ?

**Comment by MarkM-dev** [comment]
Seems that twitch added this screen when there are ads running on the channels we are trying to preview.
sometimes it doesn't appear at all.
unfortunately there's nothing we can do and i don't intend on opening a front about ads, they want you to click into the channel.. 

i imagine that this is temporary in their recent push for ads and will probably be more lenient after the start of 2023.

**Comment by Loukious** [comment]
> will probably be more lenient after the start of 2023

Doesn't seem like it. It's currently ruining the experience. What's the point of previews when almost all of them require you to wait for 12 seconds? I might as well click it and enter the channel the normal way, it will be much faster.

**Comment by MarkM-dev** [comment]
use thumbnail previews
or don't use it. do whatever you like.
would you like me to disable previews altogether? oh wait, other people still want the previews. oh, wait, there's a button in the settings that you can toggle things on and off. maybe use that.
