### ISSUE TITLE
Problem with the favorites list

### ISSUE THREAD

**Issue by Limekys** [MarkM-dev/Previews#106]
Some channels that have changed their nickname remain on the list and there is no way to remove them.
In red I marked the same channel which was first called Steigrein then mediumstein and now ogemoto, but all its variations remained in the list.
![chrome_Xx8GG75ukO](https://user-images.githubusercontent.com/58959645/202926211-25035509-0300-4839-9259-feacc1bfa5bb.png)

**Comment by MarkM-dev** [comment]
you will need to remove them manually for now:
1. open the settings and scroll down.
2. expand the Import/Export Settings section.
3. select only favorites.
![image](https://user-images.githubusercontent.com/38380938/202927598-f6a41c5f-e8ed-43bd-96be-60bba02aacce.png)
4. click export and save the file.
5. open the file with a text editor.
6. delete the object with the name you want to remove, for example, an object with mediumstein would look like this:
 `{"display_name":"mediumstein","profile_pic_url":"","stream_name":"mediumstein"}`
8. save the file.
9. go to the extension settings and click import and select the file you just saved,

**Comment by Limekys** [comment]
Thanks, I figured it out myself and did so ) Hopefully in the next updates
there will be a solution in the settings.

пн, 21 нояб. 2022 г. в 00:47, MarkM-dev ***@***.***>:
