### ISSUE TITLE
Favorite's list has a fav with a strange URL.  Can't remove it from the Fav's list

### ISSUE THREAD

**Issue by frank479** [MarkM-dev/Previews#108]
One of my favorites is showing the below URL.  So, I can't access the channel to be able to "un-favorite" the streamer.  The name show matches a second name in my favorites list that is correct (has the correct URL).  So, I remove that one from the list but still this bad one persists.

https://www.twitch.tv/Just%20Chatting#

I have no idea how this ended up in my favorites list in the first place.

**Comment by MarkM-dev** [comment]
It's an old bug that was fixed and i guess some old stuff were not deleted.
See the answer here https://github.com/MarkM-dev/Previews/issues/106#issuecomment-1321251243
