### ISSUE TITLE
Extension turns off when page is refreshed.

### ISSUE THREAD

**Issue by DannyBruv** [MarkM-dev/Previews#111]
When refreshing twitch, the extension disappears entirely and reverts twitch back to it's original layout and options.  It remains this way until I manually disable and re-enable it in my firefox addons.

**Comment by MarkM-dev** [comment]
There was an update today, i think it just updated in the background.
Seems to be working in tests.
Reopen this if the issue persists all the time.

**Comment by DannyBruv** [comment]
After multiple restarts of both firefox and my pc, the issue persists. On top of that, even when it appears that twitch previews is on and functional, I can't actually preview streams on the left bar.

Please let me know what to do.

**Comment by MarkM-dev** [comment]
1. can you share a video of what exactly is happening?
2. is it possible that other extensions are interfering?
3. maybe try disable all other extensions except Previews, then refresh twitch and see if it happens again?
4. did this start just now?
5.  how long did the extension work before this started happening?
6. does it work ok on other browsers?

**Comment by DannyBruv** [comment]
Hi, it seems to have fixed itself.

But just to answer your questions:
I turned off all of my other extensions when I was attempting to troubleshoot it, but nothing had changed. It started the day I opened this ticket (that's when I noticed it at least.) It fixed itself about a day later.
