### ISSUE TITLE
YouTube's "playback rate" keyboard shortcuts collide with SponsorBlock's keyboard shortcuts

### ISSUE THREAD

**Issue by avi12** [MarkM-dev/Previews#113]
![image](https://user-images.githubusercontent.com/6422804/209337811-8427c82c-94bf-4901-8444-6c29752228c4.png)
![image](https://user-images.githubusercontent.com/6422804/209337854-ed240fbf-1163-4039-8c71-ef5ec0effeb6.png)

**Comment by MarkM-dev** [comment]
yea its pretty hard to find shortcuts because youtube has a lot of them so it makes sense some extensions will overlap.
ill look into changing them (probably alongside some others) for the next version.

**Comment by MarkM-dev** [comment]
fixed.
