### ISSUE TITLE
constantly refreshing

### ISSUE THREAD

**Issue by tongue-puncher** [MarkM-dev/Previews#115]
tried on 2 different browsers and its constantly refreshing, even when the auto refresh is turned off, once i disable the add on it doesnt auto refresh, amazing addon minus this constant refreshing

**Comment by MarkM-dev** [comment]
what browser are you using?
have you tried disabling ALL other extensions? (refresh after).

**Comment by MarkM-dev** [comment]
no response for a long time. reopen if it persists.
