### ISSUE TITLE
Allow keyboard shortcuts to be turned off

### ISSUE THREAD

**Issue by dnestico** [MarkM-dev/Previews#117]
PLEASE allow us to turn the keyboard shortcuts off, it's very annoying that as I'm typing a comment one of them gets triggered. Much rather have the option to disable them since I rather use the button with my mouse instead, anyways.

**Comment by MarkM-dev** [comment]
that's a bug and will be fixed in the next version.
duplicate of: https://github.com/MarkM-dev/Previews/issues/114
