### ISSUE TITLE
[Feature request] Auto Claim Drops

### ISSUE THREAD

**Issue by johnnyok** [MarkM-dev/Previews#29]
It would be nice to have this functionality since in some Drops it is necessary to claim before continuing to farm the following Drops

**Comment by BigBrizzle** [comment]
I was just coming to request this as well. Seems like a modification of the function of Auto Channel Points Clicker could accomplish it pretty easily. The main drive for me is the game devs for Rust like to stack 6 or 7 items as a single giveaway and it'd be wonderful to just log into a stream and let them collect, especially for streams in inopportune time zones.
