### ISSUE TITLE
Youtube live fetch is prone to different languages

### ISSUE THREAD

**Issue by deancanen** [MarkM-dev/Previews#95]
In background,js on line 898, there is a variable that is supposed to retrieve watch count. 

However, the "runs" object has a different mapping for each language.
![image](https://user-images.githubusercontent.com/9385112/193951233-00430744-8eed-45ed-b3cc-7d81aede5917.png)

Therefore error is raised:
![image](https://user-images.githubusercontent.com/9385112/193951313-bb5ae4e9-e989-47a4-9a21-1b3d3088b45c.png)

**Comment by MarkM-dev** [comment]
ill take a look at it when i can, thanks.

**Comment by MarkM-dev** [comment]
Done.
