### ISSUE TITLE
Video previews not working on Firefox

### ISSUE THREAD

**Issue by stujii** [MarkM-dev/Previews#99]
In the Firefox browser, hovering over a channel in the sidebar shows a paused broadcast (using video preview ofc). Autoplay is enabled by default for all sites (attaching a screenshot). Chromium-based browsers do not have this problem. I suppose it's impossible to fix this because of the browser engine, or the developer already knows about the problem, but maybe I just don't know about the solution. Thank you.

![1](https://user-images.githubusercontent.com/116227818/196813812-b7db2991-e1e4-4736-9794-97792810c2fc.png)
![2](https://user-images.githubusercontent.com/116227818/196814385-3248057a-b81f-4379-a170-02681b592360.png)

**Comment by MarkM-dev** [comment]
iv'e had someone else report a similar issue and in his case it was a different extension that did that.
try disabling all other extensions, refresh twitch, and see if it still happens.

**Comment by MarkM-dev** [comment]
no response for over a month, seems to be working fine, closing.

**Comment by stujii** [comment]
Sorry for no response. Yes, the problem was in another extension (uBlock Origin). Adding the twitch to the whitelist solved this problem. Thank you
